import type { Brand } from "@/types";

export const brands: Brand[] = [
  {
    id: "miokdang",
    name: "미옥당 본점",
    letter: "미",
    industry: "restaurant",
    industryLabel: "한정식",
    city: "강남구",
    toneVersion: 3,
    brandColors: { primary: "#7B2D26", secondary: "#E9DCC0" },
    gradient: "from-rose-400 to-orange-400",
    campaign: "5월 봄나물 코스",
    followers: 12400,
    saveRate: 5.4,
    reachThisMonth: 68_000,
    isDemo: true,
  },
  {
    id: "roastery-1985",
    name: "로스터리 1985",
    letter: "R",
    industry: "cafe",
    industryLabel: "스페셜티 카페",
    city: "서촌",
    toneVersion: 2,
    brandColors: { primary: "#3B2A20", secondary: "#D4B895" },
    gradient: "from-amber-700 to-stone-800",
    campaign: "5월 콜드브루 시즌",
    followers: 8200,
    saveRate: 4.7,
    reachThisMonth: 41_200,
    isDemo: true,
  },
  {
    id: "seochon-stay",
    name: "서촌 한옥스테이",
    letter: "서",
    industry: "stay",
    industryLabel: "한옥 숙소",
    city: "종로구",
    toneVersion: 2,
    brandColors: { primary: "#4A3528", secondary: "#F5EBD6" },
    gradient: "from-amber-800 to-stone-700",
    campaign: "장마 감성 스테이",
    followers: 5800,
    saveRate: 6.1,
    reachThisMonth: 28_400,
    isDemo: true,
  },
  {
    id: "dolce-dessert",
    name: "달콤한 디저트",
    letter: "달",
    industry: "dessert",
    industryLabel: "디저트샵",
    city: "성수동",
    toneVersion: 4,
    brandColors: { primary: "#E8A8B6", secondary: "#FFF5F0" },
    gradient: "from-pink-300 to-rose-400",
    campaign: "여름 수박 케이크",
    followers: 18600,
    saveRate: 7.2,
    reachThisMonth: 92_000,
    isDemo: true,
  },
  {
    id: "luna-hair",
    name: "루나 헤어 강남점",
    letter: "루",
    industry: "beauty",
    industryLabel: "미용·헤어",
    city: "강남구",
    toneVersion: 5,
    brandColors: { primary: "#1B1B1F", secondary: "#D9B6A1" },
    gradient: "from-violet-400 to-fuchsia-500",
    campaign: "5월 봄 컬러",
    followers: 14200,
    saveRate: 4.2,
    reachThisMonth: 52_800,
    isDemo: true,
  },
  {
    id: "forum-fashion",
    name: "FORUM 패션",
    letter: "F",
    industry: "local",
    industryLabel: "컨템포러리 패션",
    city: "한남동",
    toneVersion: 6,
    brandColors: { primary: "#111111", secondary: "#E5E1DB" },
    gradient: "from-slate-700 to-zinc-900",
    campaign: "S/S 26 룩북",
    followers: 24800,
    saveRate: 3.8,
    reachThisMonth: 78_600,
    isDemo: true,
  },
];

export const getBrand = (id: string) => brands.find((b) => b.id === id);
