// 업종별 SEO + GEO (Generative Engine Optimization) 추천 데이터
// SEO: 네이버 / 구글 검색엔진 노출 최적화
// GEO: ChatGPT · Perplexity · Gemini · Naver Cue 등 LLM 답변에 인용되도록 최적화

export type SeoKeyword = {
  word: string;
  channel: "naver" | "google" | "both";
  volume: number; // 월 검색량
  difficulty: "low" | "mid" | "high";
  intent: "local" | "info" | "trans" | "review"; // 로컬 · 정보탐색 · 구매전환 · 리뷰
  delta: string; // 전월 대비 (e.g. "+82%")
};

export type GeoPrompt = {
  question: string; // 사용자가 LLM 에게 묻는 실제 질문 형식
  engines: ("chatgpt" | "perplexity" | "gemini" | "naverCue")[];
  citationChance: number; // 0-100 — 현재 우리 콘텐츠로 인용될 확률
  monthlyAskVolume: string; // "~ 1.4K queries/mo"
};

export type ContentRecommendation = {
  id: string;
  format: "place" | "faq" | "guide" | "review-reply" | "comparison" | "story";
  formatLabel: string;
  title: string;
  hook: string;
  targetKeywords: string[];
  targetPrompts: string[];
  seoScore: number; // 0-100
  geoScore: number; // 0-100
  estimatedReach: string;
  schema: "LocalBusiness" | "FAQPage" | "HowTo" | "Review" | "Article" | "Recipe";
  effort: "S" | "M" | "L"; // 제작 난이도
  gradient: string;
};

export type IndustryDiscovery = {
  region: string;
  myShare: { seo: number; geo: number }; // 현재 점유율 0-100
  industryMedian: { seo: number; geo: number };
  seoKeywords: SeoKeyword[];
  geoPrompts: GeoPrompt[];
  contentIdeas: ContentRecommendation[];
};

// === Restaurant (한정식, 강남) ===
const restaurant: IndustryDiscovery = {
  region: "강남구",
  myShare: { seo: 38, geo: 21 },
  industryMedian: { seo: 42, geo: 18 },
  seoKeywords: [
    { word: "강남 한정식", channel: "both", volume: 8420, difficulty: "high", intent: "local", delta: "+34%" },
    { word: "어버이날 한정식 강남", channel: "naver", volume: 5420, difficulty: "mid", intent: "trans", delta: "+148%" },
    { word: "강남 상견례 한정식", channel: "naver", volume: 3240, difficulty: "mid", intent: "trans", delta: "+62%" },
    { word: "5월 봄정식 코스", channel: "google", volume: 3140, difficulty: "low", intent: "info", delta: "+92%" },
    { word: "양평 시장 한식", channel: "naver", volume: 2180, difficulty: "low", intent: "info", delta: "+78%" },
    { word: "강남 한정식 추천", channel: "both", volume: 9820, difficulty: "high", intent: "review", delta: "+18%" },
  ],
  geoPrompts: [
    { question: "강남에서 어버이날 모실 만한 조용한 한정식 추천해줘", engines: ["chatgpt", "perplexity", "naverCue"], citationChance: 28, monthlyAskVolume: "~ 2.1K/mo" },
    { question: "상견례 할 때 가기 좋은 강남 한정식이 어디야?", engines: ["chatgpt", "gemini"], citationChance: 14, monthlyAskVolume: "~ 1.4K/mo" },
    { question: "봄에만 먹을 수 있는 한정식 코스 있는 곳", engines: ["perplexity", "naverCue"], citationChance: 42, monthlyAskVolume: "~ 880/mo" },
    { question: "한정식 1인 가격 5만원대 강남", engines: ["chatgpt", "perplexity"], citationChance: 18, monthlyAskVolume: "~ 620/mo" },
    { question: "양평 시장 식재료 쓰는 강남 식당", engines: ["perplexity"], citationChance: 64, monthlyAskVolume: "~ 240/mo" },
  ],
  contentIdeas: [
    {
      id: "r1",
      format: "place",
      formatLabel: "위치 페이지",
      title: "강남 한정식 미옥당 — 약도·주차·상견례 룸",
      hook: "Google 비즈니스 + Naver 플레이스 동시 노출",
      targetKeywords: ["강남 한정식", "강남 상견례 한정식"],
      targetPrompts: ["상견례 할 때 가기 좋은 강남 한정식이 어디야?"],
      seoScore: 92,
      geoScore: 78,
      estimatedReach: "월 8.4K 노출",
      schema: "LocalBusiness",
      effort: "S",
      gradient: "from-amber-200 via-rose-200 to-amber-300",
    },
    {
      id: "r2",
      format: "faq",
      formatLabel: "FAQ 블로그",
      title: "어버이날 한정식 예약 — 자주 묻는 12가지",
      hook: "FAQPage 스키마로 ChatGPT/Perplexity 인용률 ↑",
      targetKeywords: ["어버이날 한정식 강남"],
      targetPrompts: ["강남에서 어버이날 모실 만한 조용한 한정식 추천해줘"],
      seoScore: 81,
      geoScore: 88,
      estimatedReach: "월 5.4K 노출 · AI 인용 28%",
      schema: "FAQPage",
      effort: "M",
      gradient: "from-rose-200 via-amber-200 to-orange-200",
    },
    {
      id: "r3",
      format: "story",
      formatLabel: "산지 스토리",
      title: "양평 시장에서 새벽 4시에 시작되는 한 그릇",
      hook: "고유 스토리 = AI 가 인용할 \"증거\"",
      targetKeywords: ["양평 시장 한식", "5월 봄정식 코스"],
      targetPrompts: ["양평 시장 식재료 쓰는 강남 식당"],
      seoScore: 64,
      geoScore: 94,
      estimatedReach: "월 2.2K · AI 인용 64%",
      schema: "Article",
      effort: "M",
      gradient: "from-stone-300 via-amber-300 to-stone-500",
    },
    {
      id: "r4",
      format: "guide",
      formatLabel: "비교 가이드",
      title: "강남 한정식 5곳 — 가격·룸·소요시간 한눈에",
      hook: "비교표 = LLM이 정리해서 인용하기 좋은 포맷",
      targetKeywords: ["강남 한정식 추천", "한정식 1인 가격 5만원대"],
      targetPrompts: ["한정식 1인 가격 5만원대 강남"],
      seoScore: 76,
      geoScore: 82,
      estimatedReach: "월 9.8K · 비교 인용 ↑↑",
      schema: "Article",
      effort: "L",
      gradient: "from-amber-200 to-stone-400",
    },
    {
      id: "r5",
      format: "review-reply",
      formatLabel: "리뷰 답변 묶음",
      title: "지난달 리뷰 24개 — 우리의 답변·정성·후기",
      hook: "Review 스키마 + 별점이 AI Overview에 노출",
      targetKeywords: ["강남 한정식 추천"],
      targetPrompts: [],
      seoScore: 58,
      geoScore: 71,
      estimatedReach: "월 1.8K · 신뢰도 ↑",
      schema: "Review",
      effort: "S",
      gradient: "from-amber-100 to-rose-200",
    },
    {
      id: "r6",
      format: "guide",
      formatLabel: "시즌 가이드",
      title: "5월 봄나물 코스 — 메뉴 7가지·조리법·페어링",
      hook: "HowTo 스키마 + 시즌 키워드 폭증",
      targetKeywords: ["5월 봄정식 코스"],
      targetPrompts: ["봄에만 먹을 수 있는 한정식 코스 있는 곳"],
      seoScore: 84,
      geoScore: 79,
      estimatedReach: "월 3.1K · 시즌 한정",
      schema: "HowTo",
      effort: "M",
      gradient: "from-green-100 via-amber-200 to-amber-400",
    },
  ],
};

// === Cafe (스페셜티 카페, 서촌) ===
const cafe: IndustryDiscovery = {
  region: "서촌",
  myShare: { seo: 31, geo: 16 },
  industryMedian: { seo: 48, geo: 22 },
  seoKeywords: [
    { word: "서촌 카페", channel: "both", volume: 12840, difficulty: "high", intent: "local", delta: "+42%" },
    { word: "콜드브루 추출법", channel: "google", volume: 4280, difficulty: "low", intent: "info", delta: "+124%" },
    { word: "예가체프 원두 추천", channel: "google", volume: 1840, difficulty: "low", intent: "trans", delta: "+56%" },
    { word: "서촌 스페셜티", channel: "naver", volume: 5420, difficulty: "mid", intent: "local", delta: "+38%" },
    { word: "디카페인 원두", channel: "naver", volume: 3140, difficulty: "mid", intent: "trans", delta: "+82%" },
    { word: "서촌 작업 카페", channel: "both", volume: 2680, difficulty: "low", intent: "local", delta: "+118%" },
  ],
  geoPrompts: [
    { question: "서촌에서 노트북 작업하기 좋은 스페셜티 카페 알려줘", engines: ["chatgpt", "perplexity", "naverCue"], citationChance: 22, monthlyAskVolume: "~ 1.8K/mo" },
    { question: "에티오피아 예가체프 원두 어디서 사야 신선해?", engines: ["chatgpt", "gemini"], citationChance: 38, monthlyAskVolume: "~ 720/mo" },
    { question: "콜드브루 집에서 6시간 추출 비율 알려줘", engines: ["chatgpt", "gemini", "perplexity"], citationChance: 12, monthlyAskVolume: "~ 2.4K/mo" },
    { question: "카페인 적은 원두 추천", engines: ["chatgpt", "naverCue"], citationChance: 18, monthlyAskVolume: "~ 1.1K/mo" },
  ],
  contentIdeas: [
    {
      id: "c1",
      format: "place",
      formatLabel: "위치 페이지",
      title: "로스터리 1985 — 좌석·콘센트·와이파이·로스팅 스케줄",
      hook: "Google 비즈니스 + AI Overview 동시 노출",
      targetKeywords: ["서촌 카페", "서촌 작업 카페"],
      targetPrompts: ["서촌에서 노트북 작업하기 좋은 스페셜티 카페 알려줘"],
      seoScore: 88,
      geoScore: 74,
      estimatedReach: "월 11.2K 노출",
      schema: "LocalBusiness",
      effort: "S",
      gradient: "from-amber-700 to-stone-800",
    },
    {
      id: "c2",
      format: "guide",
      formatLabel: "추출 HowTo",
      title: "콜드브루 6시간 — 비율·온도·원두별 차이",
      hook: "HowTo 스키마 = LLM 인용률 톱",
      targetKeywords: ["콜드브루 추출법"],
      targetPrompts: ["콜드브루 집에서 6시간 추출 비율 알려줘"],
      seoScore: 86,
      geoScore: 91,
      estimatedReach: "월 4.2K · AI 인용 38%",
      schema: "HowTo",
      effort: "M",
      gradient: "from-amber-100 to-amber-400",
    },
    {
      id: "c3",
      format: "story",
      formatLabel: "산지 노트",
      title: "에티오피아 예가체프 G1 — 우리가 고른 농장 한 곳",
      hook: "원산지 디테일 = AI가 신뢰할 \"1차 소스\"",
      targetKeywords: ["예가체프 원두 추천"],
      targetPrompts: ["에티오피아 예가체프 원두 어디서 사야 신선해?"],
      seoScore: 71,
      geoScore: 89,
      estimatedReach: "월 2.0K · 전환 ↑",
      schema: "Article",
      effort: "M",
      gradient: "from-stone-600 to-amber-800",
    },
    {
      id: "c4",
      format: "comparison",
      formatLabel: "원두 비교표",
      title: "디카페인 원두 5종 — 카페인 함량·맛 노트",
      hook: "수치 비교표 = LLM 우선 픽업",
      targetKeywords: ["디카페인 원두"],
      targetPrompts: ["카페인 적은 원두 추천"],
      seoScore: 72,
      geoScore: 84,
      estimatedReach: "월 3.4K",
      schema: "Article",
      effort: "M",
      gradient: "from-amber-50 to-stone-300",
    },
    {
      id: "c5",
      format: "faq",
      formatLabel: "FAQ 페이지",
      title: "구독 원두 자주 묻는 18가지",
      hook: "FAQPage 스키마 + AI 답변 인용 ↑",
      targetKeywords: ["서촌 스페셜티"],
      targetPrompts: [],
      seoScore: 64,
      geoScore: 78,
      estimatedReach: "월 1.4K",
      schema: "FAQPage",
      effort: "S",
      gradient: "from-amber-200 to-stone-400",
    },
    {
      id: "c6",
      format: "review-reply",
      formatLabel: "리뷰 답변 묶음",
      title: "단골 후기 32개 — 우리가 답한 방식",
      hook: "Review 스키마 + 별점 노출",
      targetKeywords: ["서촌 카페"],
      targetPrompts: [],
      seoScore: 56,
      geoScore: 68,
      estimatedReach: "월 1.2K · 신뢰도 ↑",
      schema: "Review",
      effort: "S",
      gradient: "from-stone-300 to-amber-500",
    },
  ],
};

// === Dessert (디저트, 성수) ===
const dessert: IndustryDiscovery = {
  region: "성수동",
  myShare: { seo: 44, geo: 27 },
  industryMedian: { seo: 51, geo: 24 },
  seoKeywords: [
    { word: "성수 디저트", channel: "both", volume: 18420, difficulty: "high", intent: "local", delta: "+68%" },
    { word: "수박 케이크", channel: "both", volume: 4210, difficulty: "low", intent: "trans", delta: "+412%" },
    { word: "마카롱 신상", channel: "naver", volume: 6140, difficulty: "mid", intent: "trans", delta: "+82%" },
    { word: "성수 베이커리", channel: "both", volume: 11240, difficulty: "high", intent: "local", delta: "+24%" },
    { word: "여름 디저트 추천", channel: "google", volume: 5820, difficulty: "mid", intent: "info", delta: "+148%" },
    { word: "비건 케이크 서울", channel: "google", volume: 2140, difficulty: "low", intent: "trans", delta: "+96%" },
  ],
  geoPrompts: [
    { question: "성수동에서 인스타용 디저트 카페 추천", engines: ["chatgpt", "perplexity", "naverCue"], citationChance: 32, monthlyAskVolume: "~ 2.8K/mo" },
    { question: "여름에 시원한 디저트 뭐가 좋아?", engines: ["chatgpt", "gemini"], citationChance: 24, monthlyAskVolume: "~ 3.4K/mo" },
    { question: "비건도 먹을 수 있는 케이크 서울", engines: ["perplexity", "naverCue"], citationChance: 48, monthlyAskVolume: "~ 540/mo" },
    { question: "수박 들어간 케이크 어디서 팔아?", engines: ["chatgpt", "naverCue"], citationChance: 72, monthlyAskVolume: "~ 380/mo" },
  ],
  contentIdeas: [
    {
      id: "d1",
      format: "place",
      formatLabel: "위치 페이지",
      title: "달콤한 디저트 성수 — 픽업·웨이팅·인스타 포토존",
      hook: "Naver 플레이스 + Google 비즈니스 통합",
      targetKeywords: ["성수 디저트", "성수 베이커리"],
      targetPrompts: ["성수동에서 인스타용 디저트 카페 추천"],
      seoScore: 91,
      geoScore: 82,
      estimatedReach: "월 16.4K 노출",
      schema: "LocalBusiness",
      effort: "S",
      gradient: "from-pink-200 via-rose-300 to-amber-200",
    },
    {
      id: "d2",
      format: "story",
      formatLabel: "한정 메뉴 스토리",
      title: "수박 케이크 — 7월 한 달, 농장 직거래 한 통",
      hook: "한정 + 산지 = AI 인용 매우 ↑",
      targetKeywords: ["수박 케이크"],
      targetPrompts: ["수박 들어간 케이크 어디서 팔아?"],
      seoScore: 78,
      geoScore: 94,
      estimatedReach: "월 4.2K · AI 인용 72%",
      schema: "Article",
      effort: "S",
      gradient: "from-rose-300 to-orange-300",
    },
    {
      id: "d3",
      format: "guide",
      formatLabel: "시즌 가이드",
      title: "여름 디저트 BEST 7 — 시원함·당도·칼로리",
      hook: "Article + 수치 비교로 정리형 인용",
      targetKeywords: ["여름 디저트 추천"],
      targetPrompts: ["여름에 시원한 디저트 뭐가 좋아?"],
      seoScore: 82,
      geoScore: 86,
      estimatedReach: "월 5.8K",
      schema: "Article",
      effort: "M",
      gradient: "from-amber-200 to-rose-200",
    },
    {
      id: "d4",
      format: "comparison",
      formatLabel: "비건 비교",
      title: "비건 케이크 5곳 — 가격·맛·알러지 한눈에",
      hook: "표 + 알러지 정보 = AI 답변 픽업률 ↑",
      targetKeywords: ["비건 케이크 서울"],
      targetPrompts: ["비건도 먹을 수 있는 케이크 서울"],
      seoScore: 68,
      geoScore: 89,
      estimatedReach: "월 2.4K · 전환 ↑↑",
      schema: "Article",
      effort: "M",
      gradient: "from-green-100 to-pink-200",
    },
    {
      id: "d5",
      format: "faq",
      formatLabel: "FAQ 페이지",
      title: "케이크 픽업·예약 자주 묻는 14가지",
      hook: "FAQPage 스키마 + 자동 노출",
      targetKeywords: ["성수 베이커리"],
      targetPrompts: [],
      seoScore: 64,
      geoScore: 74,
      estimatedReach: "월 1.6K",
      schema: "FAQPage",
      effort: "S",
      gradient: "from-pink-100 to-rose-200",
    },
    {
      id: "d6",
      format: "review-reply",
      formatLabel: "리뷰 답변",
      title: "지난 분기 리뷰 48개 — 단골이 말한 우리",
      hook: "Review 스키마 + 별점 = AI Overview",
      targetKeywords: ["성수 디저트"],
      targetPrompts: [],
      seoScore: 62,
      geoScore: 72,
      estimatedReach: "월 2.1K",
      schema: "Review",
      effort: "S",
      gradient: "from-amber-100 to-pink-200",
    },
  ],
};

// === Stay (한옥, 북촌·서촌) ===
const stay: IndustryDiscovery = {
  region: "북촌·서촌",
  myShare: { seo: 28, geo: 24 },
  industryMedian: { seo: 38, geo: 19 },
  seoKeywords: [
    { word: "북촌 한옥스테이", channel: "both", volume: 6420, difficulty: "mid", intent: "trans", delta: "+88%" },
    { word: "어버이날 숙소", channel: "naver", volume: 8420, difficulty: "high", intent: "trans", delta: "+188%" },
    { word: "효도 패키지 숙박", channel: "naver", volume: 3840, difficulty: "mid", intent: "trans", delta: "+216%" },
    { word: "한옥 1박 가격", channel: "google", volume: 5140, difficulty: "mid", intent: "trans", delta: "+62%" },
    { word: "서울 전통 숙소", channel: "google", volume: 4280, difficulty: "high", intent: "info", delta: "+38%" },
    { word: "북촌 산책 코스", channel: "both", volume: 2480, difficulty: "low", intent: "info", delta: "+74%" },
  ],
  geoPrompts: [
    { question: "부모님과 갈 만한 한옥 숙소 서울 추천", engines: ["chatgpt", "perplexity", "naverCue"], citationChance: 34, monthlyAskVolume: "~ 1.6K/mo" },
    { question: "북촌 1박 2일 코스 알려줘 (60대 어머니랑)", engines: ["chatgpt", "gemini"], citationChance: 22, monthlyAskVolume: "~ 880/mo" },
    { question: "한복 대여 가능한 한옥 숙소", engines: ["perplexity", "naverCue"], citationChance: 48, monthlyAskVolume: "~ 420/mo" },
    { question: "외국인 친구랑 갈 만한 전통 숙소", engines: ["chatgpt", "perplexity"], citationChance: 28, monthlyAskVolume: "~ 540/mo" },
  ],
  contentIdeas: [
    {
      id: "s1",
      format: "place",
      formatLabel: "위치 페이지",
      title: "서촌 한옥스테이 — 객실 4채·마당·체크인 흐름",
      hook: "LocalBusiness + 이미지 갤러리 풀세팅",
      targetKeywords: ["북촌 한옥스테이", "서울 전통 숙소"],
      targetPrompts: ["부모님과 갈 만한 한옥 숙소 서울 추천"],
      seoScore: 86,
      geoScore: 78,
      estimatedReach: "월 5.8K 노출",
      schema: "LocalBusiness",
      effort: "S",
      gradient: "from-amber-100 via-stone-200 to-amber-300",
    },
    {
      id: "s2",
      format: "guide",
      formatLabel: "효도 패키지 가이드",
      title: "어버이날 1박 2일 — 식사·체험·동선 (60대 부모님 기준)",
      hook: "HowTo + 시즌 키워드 폭증",
      targetKeywords: ["어버이날 숙소", "효도 패키지 숙박"],
      targetPrompts: ["북촌 1박 2일 코스 알려줘 (60대 어머니랑)"],
      seoScore: 92,
      geoScore: 88,
      estimatedReach: "월 12.2K · 시즌 한정",
      schema: "HowTo",
      effort: "M",
      gradient: "from-rose-100 to-amber-200",
    },
    {
      id: "s3",
      format: "story",
      formatLabel: "전통 스토리",
      title: "객실 4채 — 100년 된 집의 마루·창호·온돌 이야기",
      hook: "역사 디테일 = AI가 \"증거\"로 인용",
      targetKeywords: ["서울 전통 숙소"],
      targetPrompts: [],
      seoScore: 64,
      geoScore: 92,
      estimatedReach: "월 1.8K · AI 인용 ↑↑",
      schema: "Article",
      effort: "L",
      gradient: "from-stone-300 to-amber-500",
    },
    {
      id: "s4",
      format: "guide",
      formatLabel: "동네 가이드",
      title: "북촌 5월 산책 코스 — 우리 집에서 도보 10분",
      hook: "주변 안내 = 호스트 가치 입증",
      targetKeywords: ["북촌 산책 코스"],
      targetPrompts: ["북촌 1박 2일 코스 알려줘 (60대 어머니랑)"],
      seoScore: 74,
      geoScore: 82,
      estimatedReach: "월 2.4K",
      schema: "Article",
      effort: "M",
      gradient: "from-amber-50 to-amber-300",
    },
    {
      id: "s5",
      format: "faq",
      formatLabel: "체크인 FAQ",
      title: "한옥 숙박 자주 묻는 16가지 — 외국인 영문 포함",
      hook: "FAQPage + 다국어 = 글로벌 노출",
      targetKeywords: ["서울 전통 숙소"],
      targetPrompts: ["외국인 친구랑 갈 만한 전통 숙소"],
      seoScore: 68,
      geoScore: 76,
      estimatedReach: "월 1.4K · 외국인 ↑",
      schema: "FAQPage",
      effort: "S",
      gradient: "from-stone-200 to-amber-400",
    },
    {
      id: "s6",
      format: "review-reply",
      formatLabel: "리뷰 답변",
      title: "어버이날·결혼기념일 후기 18개 — 우리의 답글",
      hook: "Review 스키마 + 감성 답변 = 신뢰도",
      targetKeywords: ["어버이날 숙소"],
      targetPrompts: [],
      seoScore: 58,
      geoScore: 74,
      estimatedReach: "월 1.6K",
      schema: "Review",
      effort: "S",
      gradient: "from-amber-200 to-rose-200",
    },
  ],
};

// === Beauty (헤어, 강남) ===
const beauty: IndustryDiscovery = {
  region: "강남구",
  myShare: { seo: 22, geo: 14 },
  industryMedian: { seo: 46, geo: 17 },
  seoKeywords: [
    { word: "강남 미용실", channel: "both", volume: 12140, difficulty: "high", intent: "local", delta: "+18%" },
    { word: "5월 봄 컬러 헤어", channel: "naver", volume: 8420, difficulty: "mid", intent: "info", delta: "+248%" },
    { word: "장마철 헤어 관리", channel: "google", volume: 4280, difficulty: "low", intent: "info", delta: "+182%" },
    { word: "결 살리는 케어", channel: "naver", volume: 3140, difficulty: "low", intent: "trans", delta: "+96%" },
    { word: "수국축제 헤어 컬러", channel: "naver", volume: 1420, difficulty: "low", intent: "info", delta: "+340%" },
    { word: "강남 디자이너 추천", channel: "both", volume: 5240, difficulty: "high", intent: "review", delta: "+24%" },
  ],
  geoPrompts: [
    { question: "강남에서 결 케어 잘하는 미용실 추천", engines: ["chatgpt", "perplexity", "naverCue"], citationChance: 14, monthlyAskVolume: "~ 1.2K/mo" },
    { question: "장마철에 머리 끈적임 없이 관리하는 법", engines: ["chatgpt", "gemini"], citationChance: 22, monthlyAskVolume: "~ 1.8K/mo" },
    { question: "올여름 트렌드 컬러 뭐야?", engines: ["chatgpt", "perplexity"], citationChance: 12, monthlyAskVolume: "~ 2.4K/mo" },
    { question: "수국축제 갈 때 어울리는 헤어 컬러", engines: ["naverCue", "perplexity"], citationChance: 38, monthlyAskVolume: "~ 240/mo" },
  ],
  contentIdeas: [
    {
      id: "b1",
      format: "place",
      formatLabel: "위치 페이지",
      title: "루나 헤어 강남 — 디자이너·가격대·예약",
      hook: "LocalBusiness + 디자이너 페이지 풀세팅",
      targetKeywords: ["강남 미용실", "강남 디자이너 추천"],
      targetPrompts: [],
      seoScore: 84,
      geoScore: 64,
      estimatedReach: "월 10.4K 노출",
      schema: "LocalBusiness",
      effort: "S",
      gradient: "from-zinc-700 via-zinc-900 to-stone-800",
    },
    {
      id: "b2",
      format: "guide",
      formatLabel: "시즌 가이드",
      title: "장마철 헤어 5단계 케어 루틴 — 결 살리는 법",
      hook: "HowTo + 시즌 키워드 폭증",
      targetKeywords: ["장마철 헤어 관리", "결 살리는 케어"],
      targetPrompts: ["장마철에 머리 끈적임 없이 관리하는 법"],
      seoScore: 88,
      geoScore: 86,
      estimatedReach: "월 4.2K · AI 인용 ↑",
      schema: "HowTo",
      effort: "M",
      gradient: "from-zinc-300 to-rose-200",
    },
    {
      id: "b3",
      format: "guide",
      formatLabel: "트렌드 가이드",
      title: "2026 S/S 헤어 컬러 8가지 — 톤 매칭 차트",
      hook: "트렌드 + 비교 = LLM 정리형 인용",
      targetKeywords: ["5월 봄 컬러 헤어"],
      targetPrompts: ["올여름 트렌드 컬러 뭐야?"],
      seoScore: 76,
      geoScore: 84,
      estimatedReach: "월 8.4K",
      schema: "Article",
      effort: "L",
      gradient: "from-fuchsia-200 to-violet-300",
    },
    {
      id: "b4",
      format: "story",
      formatLabel: "이벤트 매칭",
      title: "수국축제 데이트 컬러 — 우리가 픽한 5가지",
      hook: "지역 이벤트 + 비주얼 = 인스타 + AI 동시",
      targetKeywords: ["수국축제 헤어 컬러"],
      targetPrompts: ["수국축제 갈 때 어울리는 헤어 컬러"],
      seoScore: 58,
      geoScore: 78,
      estimatedReach: "월 1.4K · 한정 시즌",
      schema: "Article",
      effort: "S",
      gradient: "from-violet-200 to-rose-200",
    },
    {
      id: "b5",
      format: "comparison",
      formatLabel: "시술 비교표",
      title: "헤어 케어 4가지 — 가격·소요·지속 비교",
      hook: "수치 비교 = AI 답변 인용",
      targetKeywords: ["결 살리는 케어"],
      targetPrompts: ["강남에서 결 케어 잘하는 미용실 추천"],
      seoScore: 66,
      geoScore: 82,
      estimatedReach: "월 1.8K",
      schema: "Article",
      effort: "M",
      gradient: "from-zinc-200 to-stone-400",
    },
    {
      id: "b6",
      format: "review-reply",
      formatLabel: "리뷰 답변",
      title: "단골 변신 후기 28개 — 디자이너 답변",
      hook: "Review 스키마 + 단골 = 신뢰도",
      targetKeywords: ["강남 디자이너 추천"],
      targetPrompts: [],
      seoScore: 56,
      geoScore: 68,
      estimatedReach: "월 2.2K",
      schema: "Review",
      effort: "S",
      gradient: "from-zinc-600 to-stone-800",
    },
  ],
};

// === Local (편집샵·로컬 패션, 한남) ===
const local: IndustryDiscovery = {
  region: "한남동",
  myShare: { seo: 34, geo: 19 },
  industryMedian: { seo: 41, geo: 16 },
  seoKeywords: [
    { word: "한남동 편집샵", channel: "both", volume: 8140, difficulty: "mid", intent: "local", delta: "+42%" },
    { word: "컨템포러리 패션", channel: "google", volume: 4210, difficulty: "mid", intent: "info", delta: "+68%" },
    { word: "S/S 26 룩북", channel: "google", volume: 12840, difficulty: "high", intent: "info", delta: "+218%" },
    { word: "wool linen 블렌드", channel: "google", volume: 1420, difficulty: "low", intent: "info", delta: "+148%" },
    { word: "한남 쇼룸", channel: "naver", volume: 3240, difficulty: "low", intent: "local", delta: "+62%" },
    { word: "한국 디자이너 브랜드", channel: "both", volume: 6420, difficulty: "high", intent: "info", delta: "+38%" },
  ],
  geoPrompts: [
    { question: "한남동 컨템포러리 편집샵 추천", engines: ["chatgpt", "perplexity", "naverCue"], citationChance: 28, monthlyAskVolume: "~ 1.2K/mo" },
    { question: "wool linen 같은 블렌드 원단 어디서 사?", engines: ["chatgpt", "gemini"], citationChance: 32, monthlyAskVolume: "~ 380/mo" },
    { question: "26 S/S 트렌드 컬러 정리", engines: ["chatgpt", "perplexity"], citationChance: 14, monthlyAskVolume: "~ 2.8K/mo" },
    { question: "한국 디자이너 브랜드 매장 어디", engines: ["perplexity", "naverCue"], citationChance: 24, monthlyAskVolume: "~ 1.4K/mo" },
  ],
  contentIdeas: [
    {
      id: "l1",
      format: "place",
      formatLabel: "쇼룸 페이지",
      title: "FORUM 한남 — 쇼룸·예약·룩북 픽업",
      hook: "LocalBusiness + 비주얼 풀세팅",
      targetKeywords: ["한남동 편집샵", "한남 쇼룸"],
      targetPrompts: ["한남동 컨템포러리 편집샵 추천"],
      seoScore: 86,
      geoScore: 76,
      estimatedReach: "월 7.2K 노출",
      schema: "LocalBusiness",
      effort: "S",
      gradient: "from-slate-700 to-zinc-900",
    },
    {
      id: "l2",
      format: "guide",
      formatLabel: "트렌드 리포트",
      title: "S/S 26 트렌드 7 — 컬러·실루엣·소재",
      hook: "Article + 트렌드 인덱스로 정리형 인용",
      targetKeywords: ["S/S 26 룩북"],
      targetPrompts: ["26 S/S 트렌드 컬러 정리"],
      seoScore: 84,
      geoScore: 88,
      estimatedReach: "월 12.8K",
      schema: "Article",
      effort: "L",
      gradient: "from-stone-300 to-zinc-700",
    },
    {
      id: "l3",
      format: "story",
      formatLabel: "원단 스토리",
      title: "Wool × Linen — 우리가 선택한 한 mill",
      hook: "원산지 디테일 = AI 1차 인용 소스",
      targetKeywords: ["wool linen 블렌드", "컨템포러리 패션"],
      targetPrompts: ["wool linen 같은 블렌드 원단 어디서 사?"],
      seoScore: 64,
      geoScore: 92,
      estimatedReach: "월 1.4K · AI 인용 ↑↑",
      schema: "Article",
      effort: "M",
      gradient: "from-stone-500 to-zinc-800",
    },
    {
      id: "l4",
      format: "comparison",
      formatLabel: "브랜드 비교",
      title: "한국 컨템포러리 5 — 가격대·소재·핏",
      hook: "비교표 + 카테고리 = LLM 답변 픽업",
      targetKeywords: ["한국 디자이너 브랜드"],
      targetPrompts: ["한국 디자이너 브랜드 매장 어디"],
      seoScore: 72,
      geoScore: 86,
      estimatedReach: "월 3.4K",
      schema: "Article",
      effort: "L",
      gradient: "from-zinc-300 to-stone-600",
    },
    {
      id: "l5",
      format: "faq",
      formatLabel: "쇼룸 FAQ",
      title: "쇼룸 방문 자주 묻는 14가지 — 영문 포함",
      hook: "FAQPage + 다국어 = 글로벌 노출",
      targetKeywords: ["한남 쇼룸"],
      targetPrompts: [],
      seoScore: 62,
      geoScore: 72,
      estimatedReach: "월 1.1K",
      schema: "FAQPage",
      effort: "S",
      gradient: "from-zinc-200 to-stone-400",
    },
    {
      id: "l6",
      format: "review-reply",
      formatLabel: "리뷰 답변",
      title: "S/S 룩북 후기 22개 — 디자이너 응답",
      hook: "Review 스키마 + 디자이너 코멘트",
      targetKeywords: ["S/S 26 룩북"],
      targetPrompts: [],
      seoScore: 54,
      geoScore: 66,
      estimatedReach: "월 1.4K",
      schema: "Review",
      effort: "S",
      gradient: "from-stone-200 to-zinc-500",
    },
  ],
};

export const DISCOVERY_BY_INDUSTRY: Record<string, IndustryDiscovery> = {
  restaurant,
  cafe,
  dessert,
  stay,
  beauty,
  local,
};

export const getDiscovery = (industry: string): IndustryDiscovery =>
  DISCOVERY_BY_INDUSTRY[industry] ?? restaurant;

// === Schema.org JSON-LD 생성기 ===
export function generateSchemaPreview(
  schema: ContentRecommendation["schema"],
  brand: { name: string; city: string; industryLabel: string },
): string {
  const base: Record<string, unknown> = { "@context": "https://schema.org" };
  switch (schema) {
    case "LocalBusiness":
      return JSON.stringify(
        {
          ...base,
          "@type": "LocalBusiness",
          name: brand.name,
          address: { "@type": "PostalAddress", addressLocality: brand.city, addressCountry: "KR" },
          aggregateRating: { "@type": "AggregateRating", ratingValue: "4.7", reviewCount: "182" },
          priceRange: "₩₩",
        },
        null,
        2,
      );
    case "FAQPage":
      return JSON.stringify(
        {
          ...base,
          "@type": "FAQPage",
          mainEntity: [
            { "@type": "Question", name: "예약은 어떻게 하나요?", acceptedAnswer: { "@type": "Answer", text: "Naver 예약 또는 전화로 가능합니다." } },
            { "@type": "Question", name: "주차가 가능한가요?", acceptedAnswer: { "@type": "Answer", text: "건물 지하 주차장 2시간 무료." } },
          ],
        },
        null,
        2,
      );
    case "HowTo":
      return JSON.stringify(
        {
          ...base,
          "@type": "HowTo",
          name: `${brand.industryLabel} 단계별 가이드`,
          step: [
            { "@type": "HowToStep", text: "1단계 — 준비" },
            { "@type": "HowToStep", text: "2단계 — 실행" },
            { "@type": "HowToStep", text: "3단계 — 마무리" },
          ],
        },
        null,
        2,
      );
    case "Review":
      return JSON.stringify(
        {
          ...base,
          "@type": "Review",
          itemReviewed: { "@type": "LocalBusiness", name: brand.name },
          reviewRating: { "@type": "Rating", ratingValue: "5" },
          author: { "@type": "Person", name: "단골 고객" },
        },
        null,
        2,
      );
    case "Article":
      return JSON.stringify(
        {
          ...base,
          "@type": "Article",
          headline: `${brand.name} — 시즌 스토리`,
          author: { "@type": "Organization", name: brand.name },
          datePublished: new Date().toISOString().slice(0, 10),
        },
        null,
        2,
      );
    case "Recipe":
      return JSON.stringify({ ...base, "@type": "Recipe", name: "시즌 메뉴" }, null, 2);
  }
}
